"use client";

import Link from "next/link";
import { BarChart3, Bell, Bot, CalendarClock, Clock3, LayoutDashboard, Phone, Search, Settings, Users } from "lucide-react";
import { useMemo, useState } from "react";

const calls = [
  { name: "Rahul Sharma", company: "TechFlow", time: "Today, 10:42 AM", duration: "04:32", result: "Hot Lead", type: "Outbound" },
  { name: "Priya Singh", company: "Nova Labs", time: "Today, 09:18 AM", duration: "02:18", result: "Callback", type: "Outbound" },
  { name: "Aman Gupta", company: "GrowthX", time: "Yesterday, 04:30 PM", duration: "05:41", result: "Interested", type: "Outbound" },
  { name: "Sneha Kapoor", company: "PixelWorks", time: "Yesterday, 02:12 PM", duration: "03:12", result: "Warm Lead", type: "Outbound" },
  { name: "Vikram Mehta", company: "Orbit Systems", time: "Aug 26, 11:05 AM", duration: "01:46", result: "Not Interested", type: "Outbound" },
  { name: "Neha Joshi", company: "BrightPath", time: "Aug 24, 03:48 PM", duration: "06:09", result: "No Answer", type: "Outbound" },
];

const navItems = [[LayoutDashboard, "Dashboard", "/"], [Users, "Leads", "/leads"], [Phone, "Calls", "/calls"], [CalendarClock, "Callbacks", "/callbacks"], [BarChart3, "Analytics", "/analytics"], [Bot, "AI Agent", "/ai-agent"]] as const;

export default function CallsPage() {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("All calls");
  const visibleCalls = useMemo(() => calls.filter((call) => `${call.name} ${call.company} ${call.result}`.toLowerCase().includes(query.toLowerCase()) && (filter === "All calls" || call.result === filter)), [query, filter]);

  return <Shell active="Calls" title="Calls" subtitle="Review conversations handled by your AI sales agent">
    <section className="p-5 sm:p-8">
      <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-gray-400">Activity</p><h1 className="text-3xl font-bold">Call history</h1><p className="mt-2 text-gray-500">A clear record of every prospect conversation.</p></div><button className="flex items-center justify-center gap-2 rounded-xl bg-black px-4 py-3 text-sm font-medium text-white hover:bg-gray-800"><Phone size={17} />Start a call</button></div>
      <div className="mb-6 grid grid-cols-2 gap-4 sm:grid-cols-4"><Summary label="Total calls" value="180" detail="+8.2%" /><Summary label="Talk time" value="12h 48m" detail="This week" /><Summary label="Connected" value="74%" detail="+6.1%" /><Summary label="Avg. duration" value="03:42" detail="-0:18" /></div>
      <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="flex flex-col gap-4 border-b border-gray-100 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><h2 className="text-lg font-semibold">Recent conversations</h2><p className="text-sm text-gray-400">{visibleCalls.length} conversations shown</p></div><div className="flex flex-col gap-3 sm:flex-row"><label className="flex items-center gap-2 rounded-xl bg-gray-100 px-3 py-2"><Search size={17} className="text-gray-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search calls..." className="w-full bg-transparent text-sm outline-none sm:w-44" /></label><select value={filter} onChange={(event) => setFilter(event.target.value)} className="rounded-xl border-0 bg-gray-100 px-3 py-2 text-sm outline-none"><option>All calls</option><option>Hot Lead</option><option>Callback</option><option>Interested</option><option>Warm Lead</option><option>No Answer</option></select></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-gray-50 text-xs uppercase tracking-wider text-gray-400"><tr><th className="px-6 py-4 font-medium">Contact</th><th className="px-4 py-4 font-medium">Date &amp; time</th><th className="px-4 py-4 font-medium">Type</th><th className="px-4 py-4 font-medium">Duration</th><th className="px-4 py-4 font-medium">Outcome</th><th className="px-6 py-4 font-medium">Action</th></tr></thead><tbody className="divide-y divide-gray-100">{visibleCalls.map((call) => <tr key={`${call.name}-${call.time}`} className="transition hover:bg-gray-50"><td className="px-6 py-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-gray-100 font-semibold">{call.name.charAt(0)}</div><div><p className="font-medium">{call.name}</p><p className="text-sm text-gray-400">{call.company}</p></div></div></td><td className="px-4 py-4 text-sm text-gray-500">{call.time}</td><td className="px-4 py-4 text-sm text-gray-500">{call.type}</td><td className="px-4 py-4 text-sm font-medium">{call.duration}</td><td className="px-4 py-4"><Outcome result={call.result} /></td><td className="px-6 py-4"><button className="inline-flex items-center gap-2 text-sm font-medium hover:underline"><Clock3 size={15} />View details</button></td></tr>)}{visibleCalls.length === 0 && <tr><td colSpan={6} className="px-6 py-12 text-center text-sm text-gray-500">No calls match your search.</td></tr>}</tbody></table></div></div>
    </section>
  </Shell>;
}

function Shell({ active, title, subtitle, children }: { active: string; title: string; subtitle: string; children: React.ReactNode }) { return <div className="min-h-screen bg-[#f7f8fc] text-gray-900"><aside className="fixed left-0 top-0 hidden h-screen w-64 border-r border-gray-200 bg-white px-5 py-6 lg:block"><div className="mb-10 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-black font-bold text-white">E</div><div><h1 className="text-lg font-bold">Elevate AI</h1><p className="text-xs text-gray-400">AI Sales Agent</p></div></div><nav className="space-y-2">{navItems.map(([Icon, label, href]) => <Link key={label} href={href} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium transition ${label === active ? "bg-black text-white" : "text-gray-500 hover:bg-gray-100 hover:text-black"}`}><Icon size={19} />{label}</Link>)}</nav><div className="absolute bottom-6 left-5 right-5"><Link href="/settings" className="flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-black"><Settings size={19} />Settings</Link></div></aside><main className="lg:ml-64"><header className="flex min-h-20 items-center justify-between border-b border-gray-200 bg-white px-5 py-4 sm:px-8"><div><h2 className="text-xl font-semibold">{title}</h2><p className="text-sm text-gray-400">{subtitle}</p></div><div className="flex items-center gap-4 sm:gap-5"><button aria-label="Notifications" className="relative"><Bell size={20} /><span className="absolute -right-1 -top-1 h-2 w-2 rounded-full bg-red-500" /></button><div className="flex h-9 w-9 items-center justify-center rounded-full bg-black text-sm font-medium text-white">M</div></div></header>{children}</main></div>; }
function Summary({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-2xl border border-gray-200 bg-white p-4 sm:p-5"><p className="text-xs text-gray-500 sm:text-sm">{label}</p><div className="mt-3 flex items-end justify-between gap-2"><p className="text-2xl font-bold sm:text-3xl">{value}</p><span className="text-xs font-medium text-green-600">{detail}</span></div></div>; }
function Outcome({ result }: { result: string }) { const colors = result === "Hot Lead" ? "bg-red-50 text-red-600" : result === "No Answer" || result === "Not Interested" ? "bg-gray-100 text-gray-500" : "bg-green-50 text-green-600"; return <span className={`rounded-full px-3 py-1 text-xs font-semibold ${colors}`}>{result}</span>; }
