"use client";

import Link from "next/link";
import { BarChart3, Bell, Bot, CalendarClock, Check, Clock3, LayoutDashboard, Phone, Plus, Settings, Users } from "lucide-react";
import { useState } from "react";

const callbacks = [
  { name: "Priya Singh", company: "Nova Labs", phone: "+91 99887 66554", time: "Today, 2:30 PM", note: "Review enterprise plan options", priority: "High" },
  { name: "Aman Gupta", company: "GrowthX", phone: "+91 91234 56789", time: "Today, 4:00 PM", note: "Send pricing and integration details", priority: "High" },
  { name: "Sneha Kapoor", company: "PixelWorks", phone: "+91 97654 32109", time: "Tomorrow, 10:00 AM", note: "Follow up after team discussion", priority: "Medium" },
  { name: "Vikram Mehta", company: "Orbit Systems", phone: "+91 90909 87654", time: "Tomorrow, 3:45 PM", note: "Share implementation timeline", priority: "Medium" },
  { name: "Neha Joshi", company: "BrightPath", phone: "+91 93456 78901", time: "Aug 30, 11:30 AM", note: "Reconnect after product launch", priority: "Low" },
];

const navItems = [[LayoutDashboard, "Dashboard", "/"], [Users, "Leads", "/leads"], [Phone, "Calls", "/calls"], [CalendarClock, "Callbacks", "/callbacks"], [BarChart3, "Analytics", "/analytics"], [Bot, "AI Agent", "/ai-agent"]] as const;

export default function CallbacksPage() {
  const [items, setItems] = useState(callbacks);
  const completeCallback = (name: string) => setItems((current) => current.filter((callback) => callback.name !== name));

  return <Shell active="Callbacks" title="Callbacks" subtitle="Stay on top of every promised follow-up">
    <section className="p-5 sm:p-8">
      <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-gray-400">Follow-up queue</p><h1 className="text-3xl font-bold">Callback schedule</h1><p className="mt-2 text-gray-500">Never let a warm conversation go cold.</p></div><button className="flex items-center justify-center gap-2 rounded-xl bg-black px-4 py-3 text-sm font-medium text-white hover:bg-gray-800"><Plus size={17} />Schedule callback</button></div>
      <div className="mb-6 grid grid-cols-2 gap-4 sm:grid-cols-4"><Summary label="Due today" value="2" detail="Priority" /><Summary label="Upcoming" value="16" detail="Next 7 days" /><Summary label="Completed" value="48" detail="This month" /><Summary label="Completion rate" value="86%" detail="+5.4%" /></div>
      <div className="grid grid-cols-1 gap-6 xl:grid-cols-[1.5fr_1fr]"><div className="overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="flex items-center justify-between border-b border-gray-100 p-5 sm:p-6"><div><h2 className="text-lg font-semibold">Upcoming callbacks</h2><p className="text-sm text-gray-400">{items.length} follow-ups remaining</p></div><button aria-label="Filter callbacks" className="rounded-xl bg-gray-100 p-2.5 text-gray-500"><CalendarClock size={17} /></button></div><div className="divide-y divide-gray-100">{items.map((callback) => <div key={callback.name} className="p-5 transition hover:bg-gray-50 sm:p-6"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-gray-100 font-semibold">{callback.name.charAt(0)}</div><div><p className="font-medium">{callback.name}</p><p className="text-sm text-gray-400">{callback.company}</p></div></div><Priority level={callback.priority} /></div><div className="mt-5 flex flex-col gap-2 text-sm sm:flex-row sm:items-center sm:justify-between"><span className="flex items-center gap-2 font-medium"><Clock3 size={16} className="text-gray-400" />{callback.time}</span><span className="text-gray-500">{callback.phone}</span></div><p className="mt-3 rounded-lg bg-gray-50 px-3 py-2 text-sm text-gray-500">{callback.note}</p><div className="mt-4 flex justify-end gap-3"><button className="flex items-center gap-2 rounded-lg border border-gray-200 px-3 py-2 text-xs font-medium text-gray-600 hover:bg-gray-100"><Clock3 size={14} />Reschedule</button><button onClick={() => completeCallback(callback.name)} className="flex items-center gap-2 rounded-lg bg-black px-3 py-2 text-xs font-medium text-white hover:bg-gray-800"><Check size={14} />Mark complete</button></div></div>)}{items.length === 0 && <div className="p-12 text-center text-sm text-gray-500">Your callback queue is clear.</div>}</div></div><div className="rounded-2xl bg-black p-6 text-white"><div className="flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/10"><CalendarClock size={22} /></div><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs text-gray-300">This week</span></div><h2 className="mt-6 text-xl font-semibold">Follow-up health</h2><p className="mt-2 text-sm leading-6 text-gray-400">Your team is keeping pace with scheduled conversations.</p><div className="mt-8 space-y-5"><Progress label="Completed on time" value="86%" width="86%" /><Progress label="Rescheduled" value="9%" width="9%" /><Progress label="Missed" value="5%" width="5%" /></div><div className="mt-8 flex items-center gap-3 border-t border-white/10 pt-5 text-sm text-gray-300"><Check size={16} className="text-green-400" /> 48 callbacks completed this month</div></div></div>
    </section>
  </Shell>;
}

function Shell({ active, title, subtitle, children }: { active: string; title: string; subtitle: string; children: React.ReactNode }) { return <div className="min-h-screen bg-[#f7f8fc] text-gray-900"><aside className="fixed left-0 top-0 hidden h-screen w-64 border-r border-gray-200 bg-white px-5 py-6 lg:block"><div className="mb-10 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-black font-bold text-white">E</div><div><h1 className="text-lg font-bold">Elevate AI</h1><p className="text-xs text-gray-400">AI Sales Agent</p></div></div><nav className="space-y-2">{navItems.map(([Icon, label, href]) => <Link key={label} href={href} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium transition ${label === active ? "bg-black text-white" : "text-gray-500 hover:bg-gray-100 hover:text-black"}`}><Icon size={19} />{label}</Link>)}</nav><div className="absolute bottom-6 left-5 right-5"><Link href="/settings" className="flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-black"><Settings size={19} />Settings</Link></div></aside><main className="lg:ml-64"><header className="flex min-h-20 items-center justify-between border-b border-gray-200 bg-white px-5 py-4 sm:px-8"><div><h2 className="text-xl font-semibold">{title}</h2><p className="text-sm text-gray-400">{subtitle}</p></div><div className="flex items-center gap-4 sm:gap-5"><button aria-label="Notifications" className="relative"><Bell size={20} /><span className="absolute -right-1 -top-1 h-2 w-2 rounded-full bg-red-500" /></button><div className="flex h-9 w-9 items-center justify-center rounded-full bg-black text-sm font-medium text-white">M</div></div></header>{children}</main></div>; }
function Summary({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-2xl border border-gray-200 bg-white p-4 sm:p-5"><p className="text-xs text-gray-500 sm:text-sm">{label}</p><div className="mt-3 flex items-end justify-between gap-2"><p className="text-2xl font-bold sm:text-3xl">{value}</p><span className="text-xs font-medium text-green-600">{detail}</span></div></div>; }
function Priority({ level }: { level: string }) { const colors = level === "High" ? "bg-red-50 text-red-600" : level === "Medium" ? "bg-yellow-50 text-yellow-600" : "bg-gray-100 text-gray-500"; return <span className={`rounded-full px-3 py-1 text-xs font-semibold ${colors}`}>{level}</span>; }
function Progress({ label, value, width }: { label: string; value: string; width: string }) { return <div><div className="mb-2 flex justify-between text-sm"><span className="text-gray-400">{label}</span><span>{value}</span></div><div className="h-1.5 rounded-full bg-white/10"><div className="h-1.5 rounded-full bg-white" style={{ width }} /></div></div>; }
